### ISSUE TITLE
Navigation: convert About navigation to a dropdown

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/website#176]
From #174 and chat conversations, the current "About" navigation link should be something clearer, while retaining the flow of the top navigation menu. The best option is likely making "About" a dropdown, and most likely renaming the menu title to a more specific phrase like "Product".

- [x] Add dropdowns for desktop and mobile
- [x] Move `about` to a new page

**Comment by agjohnson** [comment]
cc @ericholscher

This was the original plan for the menu item that was renamed to "Features". I'm still ±0 on "Product", but there is probably another word that fits well here too.

But I think even if we stick with "Product" the menu could be:

```yaml
Product:
  - How Read the Docs works (this is the current "features" page, but was meant more as a overview page originally)
  - Features:
    - Building
    - Pull request previews
    - Authentication
    - etc
  - Supported tools:
    - Sphinx
    - Mkdocs
    - Unofficial tools
```

I think this helps solve focus of the existing "features" page and still gives us a reasonable menu item name for the top navigation. It also opens up the door to expanding navigation a great deal
